AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - db/seeds.rb
    - Gemfile
    - config/initializers/wrap_parameters.rb
    - config/puma.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb